name: Deploy to GitHub Pages
on: [ push ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
